openapi: "3.0.0"
info:
  title: Todo API
  description: API for managing todo items
  version: "1.0.0"
paths:
  /todos/:
    get:
      summary: Retrieve all todo items
      responses:
        '200':
          description: A list of todo items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '201':
          description: The created todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /todos/{id}/:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Retrieve a todo item by ID
      responses:
        '200':
          description: The todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo item not found
    put:
      summary: Update a todo item by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: The updated todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo item not found
    delete:
      summary: Delete a todo item by ID
      responses:
        '204':
          description: Todo item deleted successfully
        '404':
          description: Todo item not found
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [todo, completed]
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
    TodoCreate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [todo, completed]
    TodoUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [todo, completed]
