# Generated by Django 5.0.2 on 2024-03-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('completed', 'Completed')], default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
